### ISSUE TITLE
wsc-next

### ISSUE THREAD

**Issue by Shastel** [Shastel/wsc#89]
- [ ] [Sentry](#88 ) 
- [x] #68
- [ ] [OAuth](#65) 
- [ ] Install tasks as separate modules
- [ ] Integrate WSC stat service into WSC backend
- [ ] Fix all deprecation warnings
- [ ] [Notifications](#66)
- [ ] Set setting on FE from BE
- [ ] [Disconnect users on frod](#62)
- [ ] .env
- [x] [Do smth if nick is empty](#93 )
- [x] [object Object hint](#94)
- [ ] Time traveling
- [ ] Auto scoring (realtime, and export)
- [ ] ghpage with full description of project
- [ ] score page
- [ ] add game rules page
- [ ] send task description with task data
- [ ] https support
- [ ] prerun script
- [ ] #99
